doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            RollingEntities:
                type: yml
                dir: '%kernel.project_dir%/src/Roulette/Module/Rolling/Resources/mapping/doctrineOrm'
                prefix: 'Roulette\Module\Rolling\Entity'
                is_bundle: false
